<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__vfb-3</name>
   <tag></tag>
   <elementGuidId>acb12c08-f9a5-4aa4-be9d-f79f2c4f2125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adcbe41a-941d-4998-a243-3e871c0390a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab6d7f91-935f-421e-97af-0f79d8a68a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>62b6fb4c-6725-4d29-9372-621b62945a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-3</value>
      <webElementGuid>9153be01-ce38-4bc0-978b-3aab3938afc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium  required {digits:true,maxlength:2,minlength:2} </value>
      <webElementGuid>23a12a99-f78d-4622-870a-8a3d04096d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-3&quot;)</value>
      <webElementGuid>b6c48b9d-dddf-465b-b3ab-373d78bc42d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-3']</value>
      <webElementGuid>615af436-a8be-4319-9af3-2b5c2e99d23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='item-vfb-2']/ul/li/span/input</value>
      <webElementGuid>76c818f4-166f-4194-b7bb-c2fdd3a67dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/ul/li/span/input</value>
      <webElementGuid>ae412a3e-8f08-40cc-a9f7-222e7d40806b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-3' and @id = 'vfb-3']</value>
      <webElementGuid>a62d8811-2ea5-482e-85f1-9cb82871ee58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
