<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UFT_vfb-20</name>
   <tag></tag>
   <elementGuidId>1115850a-b0d1-4805-9659-9d8a51c42721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-20-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-20-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c060d240-cddd-4a6a-92e6-2de6bb2af292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>687a13de-ab12-46dc-8c16-f67697fabda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-20[]</value>
      <webElementGuid>eb12ec91-4144-4cd3-947b-e343ca43a054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-20-2</value>
      <webElementGuid>a16eee04-5204-4b49-8bbe-8e4909d33ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TestNG</value>
      <webElementGuid>d2f39853-6414-40d9-a92a-ade97c7dc73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-checkbox  </value>
      <webElementGuid>e216e99d-5a50-4ebc-832c-4b9579fa5a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-20-2&quot;)</value>
      <webElementGuid>35e9b330-b27d-485f-bc03-84e20bd3f907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-20-2']</value>
      <webElementGuid>e985b889-96c7-483d-be01-6510adb51184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-20']/div/span[3]/input</value>
      <webElementGuid>b2f17a33-6e6b-44e6-9918-f3510e915e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/div/span[3]/input</value>
      <webElementGuid>b82182ad-65bc-491c-99de-1d2624aef469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'vfb-20[]' and @id = 'vfb-20-2']</value>
      <webElementGuid>8e25ad74-3578-4f3c-965c-464635069fec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
