<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Selenium WebDriver_vfb-20</name>
   <tag></tag>
   <elementGuidId>0e582450-8c08-4494-a9a6-084d21178078</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-20-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-20-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1f4232a-88a7-4df7-a282-0280c6100cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0c029028-a2dd-42f9-be60-7b79ce3b7001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-20[]</value>
      <webElementGuid>af12a67b-b2e2-4141-863a-20905c403996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-20-1</value>
      <webElementGuid>13eb5736-9c39-456c-ad71-2e8eff95aaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UFT</value>
      <webElementGuid>875bc222-93f9-4a4f-9576-ff38b8cb1d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-checkbox  </value>
      <webElementGuid>c0eca275-83ce-40aa-ac14-0571bd558899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-20-1&quot;)</value>
      <webElementGuid>48e5591d-5f02-4a5b-ba7e-07f6ad9e6460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-20-1']</value>
      <webElementGuid>8c1f5d54-4e59-4a83-bd15-da824f09ae6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-20']/div/span[2]/input</value>
      <webElementGuid>e002c00a-fd81-494e-975f-dcfd032cf31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/div/span[2]/input</value>
      <webElementGuid>9781fca2-9e83-4027-abfa-345265e7da23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'vfb-20[]' and @id = 'vfb-20-1']</value>
      <webElementGuid>9f969342-0ac9-4372-b252-9757da331ccb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
