<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enter your query_vfb-23</name>
   <tag></tag>
   <elementGuidId>fa8f14fc-d2c4-4797-b8e8-598006011dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='vfb-23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1ba965ef-531c-497d-af2b-091da4553b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-23</value>
      <webElementGuid>25b1f1a9-5c46-4c85-bd85-f9498cc63bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-23</value>
      <webElementGuid>c5664be9-c7ce-4374-a58f-cfa3eef3df42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-textarea  vfb-medium  </value>
      <webElementGuid>5bfd6116-ec9f-4639-b81f-5dfd1178f96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-23&quot;)</value>
      <webElementGuid>3a267129-64ac-448d-a8e7-a0b7f72d386b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='vfb-23']</value>
      <webElementGuid>8cbbf0b3-aaaa-41cc-b608-776e02adac53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-23']/div/textarea</value>
      <webElementGuid>8d547aaa-3e76-44b0-b643-24064995796c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5d339664-d010-468c-a780-78d46f07fe1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'vfb-23' and @id = 'vfb-23']</value>
      <webElementGuid>7b5148c4-4a8c-4a20-aabb-6cfbbaaaf92d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
